### ISSUE TITLE
Can't get this to build on macOS X

### ISSUE THREAD

**Issue by gingerbeardman** [ffont/BBC6Music#1]
Too many errors to report with Xcode 8.2.1 (8C1002) though looks like they're related to Swift changes?

Any ideas?

iOS & tvOS both build OK (with issues relating to icons)

**Comment by ffont** [comment]
I just tried and this happens because OSX version still has old Swift code.
Will have a look and see if it has a quick fix, I'm still using a version I compiled long ago which still works.

**Comment by ffont** [comment]
Please try again, it should work now.
The automatic code converter actually fixed it... awesome!

**Comment by gingerbeardman** [comment]
Awesome! Indeed it does.

I will open some issues and PR soon.

Thanks - handy app!

**Comment by ffont** [comment]
That sounds great!
The app is quite error prone, so any improvement will be more than welcome.
